### ISSUE TITLE
Cannot execute "RLKit version1.0.exe" because of dependency error

### ISSUE THREAD

**Issue by AdityaFariz** [kenwi/pku#3]
When I tried to execute RLKit version1.0.exe after downloaded, it failed with below error.

"This application failed to start because it could not find or
load the Qt platform plugin "windows".
Reinstalling the application may fix this problem."

I guess the .exe required dependencies for Qt related .dll.
I tried to install some versions of Qt and set windows path to them, but i cannot find good solution.

Could you tell me your environment like

- Which version of Qt are you using?
- What kind of PATH did you set?
- Do you know can I execute the program without visual studio?

Thanks so much for your confirmation!!!

**Comment by AdityaFariz** [comment]
i'm so sorry.
My name is Aditya from Indonesia.
i will ask about installation of RLKit version 1.0. 
please help me to install this software

**Comment by kenwi** [comment]
Hi,

is this related to the PK-1000 system or are you asking about general support for some other software?

**Comment by kenwi** [comment]
I see, it's the Windows version. I'll check if I can reproduce the error, and look for a solution. Which Windows version are you using?

**Comment by AdityaFariz** [comment]
hi, thank you for your attention. I use Windows 10 as the operating system. on the website https://www.seeedstudio.com/UWB-PK-1000-Standard-Edition-p-2918.html, I downloaded the software provided. namely RLKit version 1.0 and flyMCU. for the RLKit software I experienced a failure to install. I explained to the previous question. thank you. I hope you can help me

**Comment by kenwi** [comment]
> 
> 
> hi, thank you for your attention. I use Windows 10 as the operating system. on the website https://www.seeedstudio.com/UWB-PK-1000-Standard-Edition-p-2918.html, I downloaded the software provided. namely RLKit version 1.0 and flyMCU. for the RLKit software I experienced a failure to install. I explained to the previous question. thank you. I hope you can help me

Ok, thanks for the information. As I've got some free time during sunday this weekend, I will do a investigation into the issue and provide you a solution. Maybe we can get the issue closed over at the SeedBox repository in the same time. 

However, if memory serves correct: when I tested out - admittedly two years ago - the programs supplied it more looked like the programs were meant for demonstration purposes only. This was my experience: I set up the anchors, calibrated the system and then were able to watch the device being tracked in real time. That's nice and cool, and worked exactly like I expected. But with no real features besides the rendering. Not a problem in my situation though.

But if you are not a developer (as in, programmer), I fail to see the real benefit of this system by lack of software for non-developers. This might have changed during the two years since I last checked the status of the project. The reason I ended up with the 1000 system is really beceause I got hired to write some software running under ROS (Robot Operating System), which needed linux software which was (at least two years ago) not supplied. So for me as a programmer I'm completely satisfied with the system as programming for the system goes. 

I quess the question I'm alluding to here: are you a programmer yourself? And are you working on a project that will utilize the PK-1000?

**Comment by AdityaFariz** [comment]
Ok, thank you for your willingness to help me. I really hope that you can help solve this problem.

I am very impressed because you are very concerned about this. besides that you also have experience in completing previous projects using PK-1000 on Linux OS.
on the information on the website yesterday, it was explained that this tool was provided with RLKit software and flyMCU as support for use.

I also asked what OS was used to operate PK-1000. and the answer is to use Windows 7 or 10 OS.

but when I started using RLKit software, the software failed when I installed it.

maybe you can try to download and operate the software on Windows 7 or 10.

and for your question about "I'm asking the question I'm alluding to here: are you a self-programmer? Are you working on a project that will utilize the PK-1000?"
the answer is I'm still a beginner in the field of programmers. and I am currently completing my final assignment using a PK-1000 tool. 

please help me to solve this problem.

**Comment by kenwi** [comment]
I will provide a documented solution if I manage to reproduce and fix your error in a quick and easy way. If you need adittional help to solve the problem after that I will be able to offer you a 1-on-1 consulation session if that is something that can intestest you to spend a few bucks on. It'll probably be worth it, I've got about 15 years or professional experience and tips under my belt. In the mean time, hang on while I find my equipment and reinstall the required toolsets.

**Comment by AdityaFariz** [comment]
ok thank you for your willingness to help me.
but for the consensus session you offer to spend a few dollars I can't promise.
because I'm still a student.
And I also borrow this tool from the lecturer.
I ask you to help me in this solution.
Once again I thank you.
I am waiting for your help in resolving my case.

**Comment by AdityaFariz** [comment]
Hello Mr. Kenwi, can you find a solution to this problem yesterday?

**Comment by kenwi** [comment]
Been a bit busy finishing up a project.

**Comment by AdityaFariz** [comment]
okay thank you. Im sorry, i don't know if you busy now. 
I want to ask about the program you have worked on for uwb pk-1000.
what software do you use to program pk-1000?
and how to upload the program?
thank you sir kenwi.

**Comment by kenwi** [comment]
Uhm. Have you really read the documentation (the manual) of your device? In the case of this program: I used Windows as the host system and connected to the device by IP-address (se section 3.1 in the manual), and wrote the program in old-ish C, using the Linux Subsystem for Windows, where I compiled it and connected to the device address.

Clone the repository, run cmake and make as the readme.md says.

https://github.com/kenwi/pku/blob/master/PK-1000_User_Manual.pdf

**Comment by AdityaFariz** [comment]
thank you for this help. I have read the file. I experienced confusion in that section. when that PK-1000 TAG is turned on then wifi is connected from pk tag to computer. with SSID and an existing password.
I really haven't tried it, because I can't open one of the software, RLKit version 1.0. for the report I have asked at the beginning that there is writing about qt windows plugin.

Did you not experience something similar to me?

**Comment by AdityaFariz** [comment]
![coba awal di rlkit](https://user-images.githubusercontent.com/48787175/56020411-4aba1300-5d31-11e9-9438-e589487bfbc0.JPG)

this is my trial. I am confused because all data is zero. can you help me explain it, Mr. Kenwi?

**Comment by kenwi** [comment]
Did you manage to connect to your device? By IP, USB or serial? :)

**Comment by AdityaFariz** [comment]
yes I managed to connect with PK-TAG using Wi-fi (my IP is 192.168.0.100).
for now I still use 3 anchors. I haven't used 4 anchors yet. does this affect the results?

**Comment by kenwi** [comment]
If you only use 3 of the anchors, I believe it might have a little problem with evaluating the Z-axis. Imagine these 3 spheres being the 3 anchors. If you see the intersection of the 3 spheres in 3D, you will get two possible points, The intersection you see on top like this 
![bilde](https://user-images.githubusercontent.com/3333105/56568032-6e454f00-65b6-11e9-9f65-f5e566f2b39c.png) and the intersection on the bottom like this
![bilde](https://user-images.githubusercontent.com/3333105/56568057-82894c00-65b6-11e9-829d-da3e3c798315.png)

Adding a fourth sphere (anchor) will possibly remove the uncertainty of the remaining axis. The intersection of 4 of these spheres should be only one point, as long as you do not put all the devices on the same level. I would try putting one of the anchors higher than the other 3. :)

![bilde](https://user-images.githubusercontent.com/3333105/56568653-bfa20e00-65b7-11e9-9fe0-6c1742e79fc7.png)

**Comment by AdityaFariz** [comment]
Okay, thank you . I began to understand this, I will try to use 4 anchors. then on the display that I sent, do you also use the same way to display?
if so, using the software (downloaded at https://github.com/SeeedDocument/UWB-PK-1000-Standard-Edition/blob/master/RLKit.zip) how do I set the anchor ID and tag ID?

**Comment by AdityaFariz** [comment]
Mr Kenwi, 
I've done it according to your instructions. by using 4 anchors I install at 4 different points. but the results I get remain the same. maybe you can give me tips or steps in the process of running this SEEED UWB PK-1000 device?

please help me in solving this problem.

Thank you

**Comment by kenwi** [comment]
Hi. Please read the manual about configuring the device, and use techsupport@pudutech.com for further inquiries. :)
